-- Tamper-evident event and snapshot chains. Hashes are server-generated by triggers.
alter table public.ecosystem_events add column if not exists previous_hash_sha256 text;
alter table public.ecosystem_events add column if not exists content_hash_sha256 text;
alter table public.ecosystem_snapshots add column if not exists previous_hash_sha256 text;
alter table public.ecosystem_snapshots add column if not exists sequence_no bigint;

create or replace function public.ecosystem_event_integrity() returns trigger
language plpgsql security definer set search_path = public as $$
declare prev text;
begin
  select content_hash_sha256 into prev from public.ecosystem_events where user_id = new.user_id order by created_at desc, id desc limit 1;
  new.previous_hash_sha256 := coalesce(prev, 'GENESIS');
  new.content_hash_sha256 := encode(digest(coalesce(new.event_type,'') || '|' || coalesce(new.user_id::text,'') || '|' || coalesce(new.world_id::text,'') || '|' || new.payload::text || '|' || new.safety_status || '|' || new.previous_hash_sha256, 'sha256'),'hex');
  return new;
end $$;

drop trigger if exists ecosystem_event_integrity on public.ecosystem_events;
create trigger ecosystem_event_integrity before insert on public.ecosystem_events for each row execute function public.ecosystem_event_integrity();

create or replace function public.ecosystem_snapshot_integrity() returns trigger
language plpgsql security definer set search_path = public as $$
declare prev text; seq bigint;
begin
  select content_hash_sha256, coalesce(sequence_no,0) into prev, seq from public.ecosystem_snapshots where user_id = new.user_id order by created_at desc, id desc limit 1;
  new.previous_hash_sha256 := coalesce(prev, 'GENESIS');
  new.sequence_no := coalesce(seq,0)+1;
  if new.content_hash_sha256 is null or new.content_hash_sha256 = '' then
    new.content_hash_sha256 := encode(digest(new.state::text || '|' || new.previous_hash_sha256 || '|' || new.schema_version, 'sha256'),'hex');
  end if;
  return new;
end $$;

drop trigger if exists ecosystem_snapshot_integrity on public.ecosystem_snapshots;
create trigger ecosystem_snapshot_integrity before insert on public.ecosystem_snapshots for each row execute function public.ecosystem_snapshot_integrity();
