create extension if not exists pgcrypto;
create table if not exists public.ecosystem_worlds(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text not null default '',safety_class text not null default 'kid_safe' check(safety_class in('kid_safe','general','restricted')),status text not null default 'active' check(status in('active','maintenance','disabled')),metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ecosystem_user_state(user_id uuid primary key references auth.users(id) on delete cascade,preferences jsonb not null default '{}',adaptation jsonb not null default '{}',active_world_id uuid references public.ecosystem_worlds(id) on delete set null,state jsonb not null default '{}',state_version bigint not null default 1,updated_at timestamptz not null default now());
create table if not exists public.ecosystem_events(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,event_type text not null,world_id uuid references public.ecosystem_worlds(id) on delete set null,payload jsonb not null default '{}',safety_status text not null default 'pending' check(safety_status in('pending','allowed','blocked','review','escalated')),created_at timestamptz not null default now());
create table if not exists public.ecosystem_snapshots(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,state jsonb not null,content_hash_sha256 text not null,schema_version text not null default '1.0.0',created_at timestamptz not null default now());
create table if not exists public.ecosystem_safety_policies(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,version text not null,rules jsonb not null default '{}',enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ecosystem_safety_decisions(id uuid primary key default gen_random_uuid(),event_id uuid references public.ecosystem_events(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,decision text not null check(decision in('allow','block','review','escalate')),reason text not null,policy_slug text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create index if not exists ecosystem_events_user_created_idx on public.ecosystem_events(user_id,created_at desc);
create index if not exists ecosystem_snapshots_user_created_idx on public.ecosystem_snapshots(user_id,created_at desc);

alter table public.ecosystem_worlds enable row level security;
alter table public.ecosystem_user_state enable row level security;
alter table public.ecosystem_events enable row level security;
alter table public.ecosystem_snapshots enable row level security;
alter table public.ecosystem_safety_policies enable row level security;
alter table public.ecosystem_safety_decisions enable row level security;
revoke all on public.ecosystem_worlds,public.ecosystem_user_state,public.ecosystem_events,public.ecosystem_snapshots,public.ecosystem_safety_policies,public.ecosystem_safety_decisions from anon;
grant select on public.ecosystem_worlds,public.ecosystem_safety_policies to authenticated;
grant select,insert,update on public.ecosystem_user_state to authenticated;
grant select,insert on public.ecosystem_events,public.ecosystem_snapshots to authenticated;
grant select on public.ecosystem_safety_decisions to authenticated;
create policy worlds_active_read on public.ecosystem_worlds for select to authenticated using(status='active');
create policy state_own on public.ecosystem_user_state for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy events_own_read on public.ecosystem_events for select to authenticated using((select auth.uid())=user_id);
create policy events_own_insert on public.ecosystem_events for insert to authenticated with check((select auth.uid())=user_id);
create policy snapshots_own_read on public.ecosystem_snapshots for select to authenticated using((select auth.uid())=user_id);
create policy snapshots_own_insert on public.ecosystem_snapshots for insert to authenticated with check((select auth.uid())=user_id);
create policy policies_enabled_read on public.ecosystem_safety_policies for select to authenticated using(enabled=true);
create policy decisions_own_read on public.ecosystem_safety_decisions for select to authenticated using((select auth.uid())=user_id);
insert into public.ecosystem_worlds(slug,name,description,safety_class,metadata) values('digital-ship','Digital Ship','The ecosystem home environment and stewardship vessel.','kid_safe','{"rooms":["Bridge","Library","Playroom","University Hall"]}'),('jarvondis-university','Digital University of Jarvondis','Learning, continuity, and companion-supported education.','kid_safe','{"lineage":["Tree of Life","Encircling Fountain","Helix of Continuity"]}') on conflict(slug) do nothing;
insert into public.ecosystem_safety_policies(slug,name,version,rules) values('sunshine-shield-core','Sunshine Shield Core','1.0.0','{"principles":["kid_safe","autonomy_preserving","non_exploitative"],"default_decision":"review"}'),('diamond-firewall-core','Diamond Firewall Core','1.0.0','{"facets":["encryption","anomaly_detection","redundancy","audit_logging"]}') on conflict(slug) do nothing;
